export const subjects = [
  "English Language",
  "Mathematics",
  "Biology",
  "Chemistry",
  "Physics",
  "Geography",
  "Economics",
  "Government",
  "Literature in English",
  "Civic Education",
  "Agricultural Science",
  "Commerce",
  "Accounting",
  "Computer Studies",
  "Technical Drawing",
  "Food and Nutrition",
  "French",
  "Yoruba",
  "Igbo",
  "Hausa",
  "Islamic Religious Studies",
  "Christian Religious Studies",
  "History",
  "Visual Arts",
  "Music",
];

export const grades = ["A1", "B2", "B3", "C4", "C5", "C6", "D7", "E8", "F9"];
